# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'desktop_wid.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(642, 390)
        self.background_label = QtWidgets.QLabel(Form)
        self.background_label.setGeometry(QtCore.QRect(10, 10, 621, 371))
        self.background_label.setStyleSheet("border-image: url(:/images/main/img1.png);\n"
"border-radius:30px;")
        self.background_label.setText("")
        self.background_label.setScaledContents(False)
        self.background_label.setObjectName("background_label")
        self.music_icon_label = QtWidgets.QLabel(Form)
        self.music_icon_label.setGeometry(QtCore.QRect(40, 40, 151, 151))
        self.music_icon_label.setStyleSheet("border-image: url(:/icons/musicly_icon.png);")
        self.music_icon_label.setText("")
        self.music_icon_label.setObjectName("music_icon_label")
        self.sol_btn = QtWidgets.QPushButton(Form)
        self.sol_btn.setGeometry(QtCore.QRect(150, 290, 61, 61))
        self.sol_btn.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}")
        self.sol_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/main/back_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sol_btn.setIcon(icon)
        self.sol_btn.setIconSize(QtCore.QSize(50, 50))
        self.sol_btn.setObjectName("sol_btn")
        self.pause_stop_btn = QtWidgets.QPushButton(Form)
        self.pause_stop_btn.setGeometry(QtCore.QRect(290, 290, 51, 61))
        self.pause_stop_btn.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}")
        self.pause_stop_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/main/play_button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pause_stop_btn.setIcon(icon1)
        self.pause_stop_btn.setIconSize(QtCore.QSize(50, 50))
        self.pause_stop_btn.setObjectName("pause_stop_btn")
        self.sag_btn = QtWidgets.QPushButton(Form)
        self.sag_btn.setGeometry(QtCore.QRect(420, 290, 61, 61))
        self.sag_btn.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}")
        self.sag_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/main/next_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.sag_btn.setIcon(icon2)
        self.sag_btn.setIconSize(QtCore.QSize(50, 50))
        self.sag_btn.setObjectName("sag_btn")
        self.random_shuffle_btn = QtWidgets.QPushButton(Form)
        self.random_shuffle_btn.setGeometry(QtCore.QRect(60, 300, 51, 41))
        self.random_shuffle_btn.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}")
        self.random_shuffle_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/main/shuffle_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.random_shuffle_btn.setIcon(icon3)
        self.random_shuffle_btn.setIconSize(QtCore.QSize(40, 40))
        self.random_shuffle_btn.setObjectName("random_shuffle_btn")
        self.like_btn = QtWidgets.QPushButton(Form)
        self.like_btn.setGeometry(QtCore.QRect(520, 300, 51, 41))
        self.like_btn.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}")
        self.like_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/main/heart_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.like_btn.setIcon(icon4)
        self.like_btn.setIconSize(QtCore.QSize(40, 40))
        self.like_btn.setObjectName("like_btn")
        self.music_slider = QtWidgets.QSlider(Form)
        self.music_slider.setGeometry(QtCore.QRect(60, 240, 501, 22))
        self.music_slider.setStyleSheet("/*Horizontales*/\n"
"QSlider::groove:horizontal{\n"
"border: 1px solid #637EB8;\n"
"background: white;\n"
"height: 7px;\n"
"border-radius: 3px;\n"
"}\n"
"QSlider::sub-page:horizontal {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #ABC7EC, stop: 1 #154A98);\n"
"border: 1px solid #777;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"background: #fff;\n"
"border: 1px solid #154A98;\n"
"height: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:horizontal{\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 #fff, stop:1 #ABC7EC);\n"
"border: 1px solid #777;\n"
"width: 5px;\n"
"margin-top: -4px;\n"
"margin-bottom: -4px;\n"
"border-radius: 2px;\n"
"}\n"
"\n"
"/*Verticales*/\n"
"QSlider::groove:vertical{\n"
"border: 1px solid #637EB8;\n"
"background: white;\n"
"width:7px;\n"
"height: 55px;\n"
"border-radius: 3px;\n"
"}\n"
"QSlider::add-page:vertical {\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"stop: 0 #ABC7EC, stop: 1 #154A98);\n"
"border: 1px solid #154A98;\n"
"width: 10px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::sub-page:vertical {\n"
"background: #fff;\n"
"border: 1px solid #777;\n"
"width: 7px;\n"
"border-radius: 4px;\n"
"}\n"
"QSlider::handle:vertical{\n"
"background: qlineargradient(x1:0, y1:0, x2:1, y2:1,\n"
"stop:0 #fff, stop:1 #ABC7EC);\n"
"border: 1px solid #777;\n"
"height: 5px;\n"
"margin-left: -4px;\n"
"margin-right: -4px;\n"
"border-radius: 2px;\n"
"}\n"
"/*Horizontales y Verticales*/\n"
"QSlider::handle:horizontal:hover,\n"
"QSlider::handle:vertical:hover{\n"
"border: 1px solid #154A98;\n"
"border-radius: 3px;\n"
"}")
        self.music_slider.setOrientation(QtCore.Qt.Horizontal)
        self.music_slider.setObjectName("music_slider")
        self.current_duration = QtWidgets.QLabel(Form)
        self.current_duration.setGeometry(QtCore.QRect(30, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.current_duration.setFont(font)
        self.current_duration.setStyleSheet("color: rgb(255, 255, 255);")
        self.current_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.current_duration.setObjectName("current_duration")
        self.end_duration = QtWidgets.QLabel(Form)
        self.end_duration.setGeometry(QtCore.QRect(510, 270, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.end_duration.setFont(font)
        self.end_duration.setStyleSheet("color: rgb(255, 255, 255);")
        self.end_duration.setAlignment(QtCore.Qt.AlignCenter)
        self.end_duration.setObjectName("end_duration")
        self.music_name_max_24 = QtWidgets.QLabel(Form)
        self.music_name_max_24.setGeometry(QtCore.QRect(220, 60, 391, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.music_name_max_24.setFont(font)
        self.music_name_max_24.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0.5);\n"
"border:1px solid transparent;\n"
"border-radius:15px;")
        self.music_name_max_24.setAlignment(QtCore.Qt.AlignCenter)
        self.music_name_max_24.setObjectName("music_name_max_24")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(580, 20, 31, 31))
        self.exit_button.setStyleSheet("QPushButton{\n"
"    background-color:transparent;\n"
"}")
        self.exit_button.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/exit_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.exit_button.setIcon(icon5)
        self.exit_button.setIconSize(QtCore.QSize(30, 30))
        self.exit_button.setObjectName("exit_button")
        self.author_name_max_12 = QtWidgets.QLabel(Form)
        self.author_name_max_12.setGeometry(QtCore.QRect(300, 120, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.author_name_max_12.setFont(font)
        self.author_name_max_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgba(0, 0, 0,0.5);\n"
"border:1px solid transparent;\n"
"border-radius:5px;")
        self.author_name_max_12.setAlignment(QtCore.Qt.AlignCenter)
        self.author_name_max_12.setObjectName("author_name_max_12")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.current_duration.setText(_translate("Form", "00:00"))
        self.end_duration.setText(_translate("Form", "02:35"))
        self.music_name_max_24.setText(_translate("Form", "Call down - slowed"))
        self.author_name_max_12.setText(_translate("Form", "<unknow>"))
import icons_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
